[package]
name = "stellar-pay-cli"
edition.workspace = true
license.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
dotenvy.workspace = true
sqlx.workspace = true
stellar-pay-api.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
